name: Build GenBuckets

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build plugin
        working-directory: GenBucketsPlugin
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: GenBuckets
          path: GenBucketsPlugin/build/libs/*.jar
